# Config file for workflows/labelling.yml

version: 1

labels:
- label: "dependencies"
  authors: ["dependabot[bot]", "pre-commit-ci[bot]"]
- label: "code quality ✨"
  authors: ["pre-commit-ci[bot]"]
