name: Check Type Completeness
on:
  pull_request:
    paths:
      - telegram/**
      - pyproject.toml
      - .github/workflows/type_completeness.yml
  push:
    branches:
      - master

jobs:
  test-type-completeness:
    name:   test-type-completeness
    runs-on: ubuntu-latest
    steps:
      - uses: Bibo-Joshi/pyright-type-completeness@1.0.1
        with:
          package-name: telegram
          python-version: 3.12
          pyright-version: ~=1.1.367
